apiVersion: v1
kind: PersistentVolume
metadata:
  name: mission-control-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/mission-control
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mission-control-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: mission-control-pv
  resources:
    requests:
      storage: 500Mi
