apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "mission-control.labels" . | nindent 4 }}
type: Opaque
data:
  API_KEY: {{ .Values.secrets.apiKey | b64enc | quote }}
